name: CI/CD
on:
  pull_request:
    branches: [ master ]
jobs:
  build_and_deploy:
    name: Build && Deploy to firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '20.x'
      - name: Install Dependencies && Build
        run: npm ci && npm run build --omit=dev
      # store the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./dist
      - name: Deploy angular app to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_INTERPERSONAL_MAP }}'
          channelId: staging
          projectId: react-interpersonal-map
